VARIABLES = [
    "DIR_INPUT",
    "DIR_TARGET",
    "DIR_SCRATCH",
    "DIR_OUTPUT",
    "DIR_SLURM_LOGS",
    "FRAGALYSIS_EXPORT_REF_URL",
    "FRAGALYSIS_EXPORT_SUBMITTER_NAME",
    "FRAGALYSIS_EXPORT_SUBMITTER_EMAIL",
    "FRAGALYSIS_EXPORT_SUBMITTER_INSTITUTION",
    "SLURM_PYTHON_SCRIPT",
    "SLURM_SUBMIT_ARGS",
    "EMAIL_ADDRESS",
    "SLURM_EMAIL_PLACE",
    "SLURM_EMAIL_COMBINE",
]

DEFAULTS = {
    "DIR_INPUT": "../INPUTS",
    "DIR_TARGET": "../TARGETS",
    "DIR_SCRATCH": "../SCRATCH",
    "DIR_OUTPUT": "../OUTPUTS",
    "FRAGALYSIS_EXPORT_REF_URL": "https://github.com/mwinokan/BulkDock",
    "SLURM_EMAIL_PLACE": "FAIL,REQUEUE,INVALID_DEPEND",
    "SLURM_EMAIL_COMBINE": "END,FAIL,INVALID_DEPEND,REQUEUE",
}
