VARIABLES = [
    "DIR_INPUT",
    "DIR_TARGET",
    "DIR_SCRATCH",
    "DIR_OUTPUT",
    "FRAGALYSIS_EXPORT_REF_URL",
    "FRAGALYSIS_EXPORT_SUBMITTER_NAME",
    "FRAGALYSIS_EXPORT_SUBMITTER_EMAIL",
    "FRAGALYSIS_EXPORT_SUBMITTER_INSTITUTION",
]

DEFAULTS = {
    "DIR_INPUT": "../INPUTS",
    "DIR_TARGET": "../TARGETS",
    "DIR_SCRATCH": "../SCRATCH",
    "DIR_OUTPUT": "../OUTPUTS",
    "FRAGALYSIS_EXPORT_REF_URL": "https://github.com/mwinokan/BulkDock",
}
